import { join } from 'node:path';
import { stringify as yamlStringify } from 'yaml';
import { type WriteResult, writeFileSafe } from '../fs-utils.js';
import { type ProjectProfile, profileRepo } from '../profiler.js';

export interface InitOptions {
  root: string;
  projectName?: string;
  overwrite?: boolean;
  dryRun?: boolean;
}

export interface InitResult {
  profile: ProjectProfile;
  files: Array<{ path: string; result: WriteResult }>;
}

function projectYaml(name: string, profile: ProjectProfile): string {
  return yamlStringify({
    schema_version: '1',
    name,
    stack: {
      runtime: profile.runtime === 'unknown' ? 'node' : profile.runtime,
      framework: profile.framework ?? undefined,
      db: profile.db,
      test_runner: profile.test_runner ?? undefined,
      package_manager: profile.package_manager === 'unknown' ? 'npm' : profile.package_manager,
    },
    sut: {
      type: profile.sut_type === 'unknown' ? 'lib' : profile.sut_type,
    },
    tags: [],
  });
}

const TESTING_MD = `# Testing — \${PROJECT_NAME}

> Generated by \`aqa init\`. Edit freely; \`aqa\` re-reads this file on every run.

## What gets tested

Each scenario in this project is a *risk* (described in \`risk-map.yaml\`) plus an *invariant* that
must hold under that risk. See \`docs/methodology/agentic-qa.md\` in the kit repo for the long form.

## How it gets tested

1. \`aqa run --profile smoke\` exercises a fast subset for inner-loop feedback.
2. \`aqa run --profile release-gate\` is the merge gate (deterministic, replayable).

## Local conventions

- Add new risks to \`risk-map.yaml\`.
- Probes/oracles can be inlined in scenarios or referenced from packs.
- Findings land under \`.aqa/runs/<id>/findings.jsonl\`. Use \`aqa replay <finding-id>\` to reproduce.
`;

function riskMapYaml(name: string): string {
  return yamlStringify({
    schema_version: '1',
    project: name,
    risks: [
      {
        id: 'r-example',
        category: 'integration',
        title: 'Replace this with a real risk',
        severity: 'medium',
        likelihood: 'possible',
        invariants: [
          {
            id: 'inv-example',
            statement:
              'Replace with a one-sentence invariant that must hold under this risk (verifiable).',
          },
        ],
      },
    ],
  });
}

/**
 * Pick the bundled packs that actually contribute scenarios for the detected
 * SUT type. `pack-core` is included as the always-on baseline; it ships risks
 * and oracles but no scenarios on its own. Anything else is added when the
 * detected type matches a pack with real scenarios — otherwise `aqa run` would
 * exit zero on a freshly-init'd project (Codex P1 in PR #24 iter 4).
 */
function packsForSutType(sutType: string): string[] {
  const base = ['pack-core'];
  switch (sutType) {
    case 'api':
      return [...base, 'pack-api-core'];
    case 'web':
      return [...base, 'pack-web-ui'];
    case 'agent':
      return [...base, 'pack-llm-agent'];
    default:
      // cli / lib / pipeline / unknown — `pack-core` alone has no scenarios.
      // Users will need to add their own pack or write `.aqa/scenarios/*.yaml`.
      return base;
  }
}

function profilesYaml(profile: ProjectProfile): string {
  const sutType = profile.sut_type === 'unknown' ? 'lib' : profile.sut_type;
  const packs = packsForSutType(sutType);
  return yamlStringify({
    schema_version: '1',
    profiles: {
      smoke: {
        schema_version: '1',
        name: 'smoke',
        execution_mode: 'orchestrator',
        llm_usage: ['scenario_generation'],
        llm_budget_usd: 5,
        parallelism: 2,
        require_deterministic_replay: false,
        packs,
      },
      'release-gate': {
        schema_version: '1',
        name: 'release-gate',
        execution_mode: 'orchestrator',
        llm_usage: ['scenario_generation'],
        llm_budget_usd: 50,
        parallelism: 4,
        require_deterministic_replay: true,
        packs,
      },
    },
  });
}

export function runInit(opts: InitOptions): InitResult {
  const profile = profileRepo(opts.root);
  // Always slugify, whether the user supplied a name or we derived one from the
  // path. The schema's `Project.name` is a strict Slug and would reject anything
  // with uppercase, spaces, or punctuation otherwise.
  const name = slugify(opts.projectName ?? lastPathSegment(opts.root));
  const writeOpts = { overwrite: opts.overwrite, dryRun: opts.dryRun };
  const targets: Array<[string, string]> = [
    [join(opts.root, '.aqa', 'project.yaml'), projectYaml(name, profile)],
    [join(opts.root, '.aqa', 'testing.md'), TESTING_MD.replaceAll('${PROJECT_NAME}', name)],
    [join(opts.root, '.aqa', 'risk-map.yaml'), riskMapYaml(name)],
    [join(opts.root, '.aqa', 'profiles.yaml'), profilesYaml(profile)],
  ];
  const files = targets.map(([path, content]) => ({
    path,
    result: writeFileSafe(path, content, writeOpts),
  }));
  return { profile, files };
}

function lastPathSegment(root: string): string {
  const parts = root.replace(/[\\/]+$/, '').split(/[\\/]/);
  return parts[parts.length - 1] ?? 'project';
}

function slugify(raw: string): string {
  return (
    raw
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, '-')
      .replace(/-{2,}/g, '-')
      .replace(/^-+|-+$/g, '') || 'project'
  );
}
